###
# get article by id

GET http://api-article.webcontent.local:80/qq6LbkPg


###
# delete article by id
DELETE http://api-article.webcontent.local:80/admin/article/0He9nc4R
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMDEiLCJlbWFpbCI6ImFkbWluMDFAZXhhbXBsZS5jb20iLCJhbGlhcyI6ImFkbWluMDEgdGVzdCIsImF2YXRhciI6Imh0dHBzOi8vZW5jcnlwdGVkLXRibjAuZ3N0YXRpYy5jb20vaW1hZ2VzP3E9dGJuJTNBQU5kOUdjUmpFaEE3MTU1ejd1eVVmYTdabXdEMjY3dzhjVk5XNFQ5NWt6VjBSZTY3R3BnWHJ3STgiLCJpYXQiOjE1NzYzODk0MDQsImV4cCI6MTU3NjM5NjYwNH0.dOoxokRC8GDYbyxNM_kGXaVgx354I8BsOVMssMmkiD0


###
# get article of given user
GET http://api-article.webcontent.local:80/admin/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMDEiLCJlbWFpbCI6ImFkbWluMDFAZXhhbXBsZS5jb20iLCJhbGlhcyI6ImFkbWluMDEgdGVzdCIsImF2YXRhciI6Imh0dHBzOi8vZW5jcnlwdGVkLXRibjAuZ3N0YXRpYy5jb20vaW1hZ2VzP3E9dGJuJTNBQU5kOUdjUmpFaEE3MTU1ejd1eVVmYTdabXdEMjY3dzhjVk5XNFQ5NWt6VjBSZTY3R3BnWHJ3STgiLCJpYXQiOjE1NzYzODk0MDQsImV4cCI6MTU3NjM5NjYwNH0.dOoxokRC8GDYbyxNM_kGXaVgx354I8BsOVMssMmkiD0


###
# create new article
POST http://api-article.webcontent.local:80/admin/article
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMDEiLCJlbWFpbCI6ImFkbWluMDFAZXhhbXBsZS5jb20iLCJhbGlhcyI6ImFkbWluMDEgdGVzdCIsImF2YXRhciI6Imh0dHBzOi8vZW5jcnlwdGVkLXRibjAuZ3N0YXRpYy5jb20vaW1hZ2VzP3E9dGJuJTNBQU5kOUdjUmpFaEE3MTU1ejd1eVVmYTdabXdEMjY3dzhjVk5XNFQ5NWt6VjBSZTY3R3BnWHJ3STgiLCJpYXQiOjE1NzYzODk0MDQsImV4cCI6MTU3NjM5NjYwNH0.dOoxokRC8GDYbyxNM_kGXaVgx354I8BsOVMssMmkiD0

{
	"title": "article title",
	"content": "เทสๆๆๆๆๆ"
}

###
# update article
POST http://api-article.webcontent.local:80/admin/article/qq6LbkPg
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMDEiLCJlbWFpbCI6ImFkbWluMDFAZXhhbXBsZS5jb20iLCJhbGlhcyI6ImFkbWluMDEgdGVzdCIsImF2YXRhciI6Imh0dHBzOi8vZW5jcnlwdGVkLXRibjAuZ3N0YXRpYy5jb20vaW1hZ2VzP3E9dGJuJTNBQU5kOUdjUmpFaEE3MTU1ejd1eVVmYTdabXdEMjY3dzhjVk5XNFQ5NWt6VjBSZTY3R3BnWHJ3STgiLCJpYXQiOjE1NzYzODk0MDQsImV4cCI6MTU3NjM5NjYwNH0.dOoxokRC8GDYbyxNM_kGXaVgx354I8BsOVMssMmkiD0

{
	"tags": ["programming", "javascript"]
}

###
# login
POST http://api-user.webcontent.local:80/auth
Content-Type: application/json

{
	"username": "admin01",
	"password": "admin01"
}